#!/bin/sh
##########################################
## Smart wrapper script for the tsocks(8) transparent socksification library
## Usage:  tsocks [OPTIONS] [application [application arguments]]
##   -on (or -off)   Add (or remove) tsocks(8) from the LD_PRELOAD variable.
##   -show (or -sh)  Show the current value of the LD_PRELOAD variable.
## With no arguments, tsocks creates a shell w/ LD_PRELOAD including tsocks(8)
## 
## Tsocks-wrapper 0.1, Copyright (C) 2009 Adam Katz <scriptsATkhopiscom>, GPLv3
##########################################
### 0.1 Rewritten from Debian's tsocks script by Tamas Szerb <toma@rulez.org>
##########################################

# Grab top double-comment lines for help:
help() { sed -e '/^## /!d' -e 's///' "`which $0 || echo $0`"; }

[ -r "$TSOCKS_LIB" ] || TSOCKS_LIB="/usr/lib/libtsocks.so"

tsocks_enable() {
  case $LD_PRELOAD in
    *$TSOCKS_LIB*) true ;; # it's already enabled, so this is a no-op
    *) export LD_PRELOAD="$TSOCKS_LIB $LD_PRELOAD" ;;
  esac
}

tsocks_disable() {
  LD_PRELOAD=`echo -n $LD_PRELOAD |sed "s:$TSOCKS_LIB *::"`
  [ -n "LD_PRELOAD" ] && export LD_PRELOAD || unset LD_PRELOAD
}

while [ "x$1" = "x-${1#?}" ]; do
  case $1 in
    -on ) tsocks_enable; exit 0 ;;
    -off ) tsocks_disable; exit 0 ;;
    -show|sh) echo "LD_PRELOAD=\"$LD_PRELOAD\""; exit 0 ;;
    -h|-?|--help ) help; exit 0 ;;
    -- ) break ;;
    -* ) help; exit 1 ;;
  esac
  shift
done

tsocks_enable

[ $# = 0 ] && set ${SHELL:-/bin/sh}

exec "$@"
