#!/bin/sh
# http://sourceforge.net/forum/forum.php?thread_id=1352634&forum_id=54983

# read in application defaults here

  # these are dummy defaults so that you can test properly
  local=127.0.0.0/255.0.0.0
  server=default-server
  type=5
  port=1080

# read in default config (/etc/tsocks.conf) here (overriding app defaults)

# read in user config (~/.tsocks.conf) here (overriding system defaults)



# now we read in the command line arguments to override the above

# display 1st arg when it exists and is unique, otherwise second arg and FALSE
get() {
  [ -n "$1" ] && [ "$1" != "$2" ] && echo "$1" || echo "$2"
}

while true; do
unset r
case $1 in
--server* ) server=`get "${1#--server=}" "$2"`; [ "$server" = "$2" ] && r=2 ;;
-s* | -d* ) server=`get "${1#-[sd]}"	 "$2"`; [ "$server" = "$2" ] && r=2 ;;
--port* ) cport=`get "${1#--port=}"	 "$2"`; [ "$cport"  = "$2" ] && r=2 ;;
-p* )		cport=`get "${1#-p}"	 "$2"`; [ "$cport"  = "$2" ] && r=2 ;;
--type* ) type=`get "${1#--type=}"	 "$2"`; [ "$type"   = "$2" ] && r=2 ;;
-t* )		type=`get "${1#-t}"	 "$2"`; [ "$type"   = "$2" ] && r=2 ;;
--local* ) local=`get "${1#--local=}"	 "$2"`; [ "$local"  = "$2" ] && r=2 ;;
-l* )		local=`get "${1#-l}"	 "$2"`; [ "$local"  = "$2" ] && r=2 ;;
* )  break ;;
esac
shift $r
done

# if syntax is "server:port" then separate into server and port
p="${server#*:}"
server="${server%:*}"
[ -z "$cport" ] && [ "$server" != "$p" ] && cport="$p"
[ -n "$cport" ] && port="$cport"


echo "server: '$server'"
echo "port: '$port'"
echo "type: '$type'"
echo "local net: '$local'"
echo "execute code: '$@'"
echo "(note, execute code will actually be passed with correct quoting)"
